name: UnbreakableBlocks
main: com.carlos.unbreakable.Main
version: 1.0.0
api-version: 1.21
description: |
  Fully-featured Unbreakable Blocks Plugin by Carlos215.
  Tracks block ownership, reinforced blocks, trust, piston/explosion protection, and more.
author: Carlos215
commands:
  unbreakable:
    description: Main command to manage unbreakable blocks
    usage: /<command> <add|remove|list|check|trust|untrust|region>
    aliases: [ublock, ub]
permissions:
  unbreakable.admin:
    description: Allows full admin control of the plugin
    default: op
  unbreakable.add:
    description: Allows adding unbreakable blocks
    default: op
  unbreakable.remove:
    description: Allows removing unbreakable blocks
    default: op
  unbreakable.list:
    description: Allows listing unbreakable blocks
    default: true
  unbreakable.check:
    description: Allows checking ownership of blocks
    default: true
  unbreakable.bypass:
    description: Allows bypassing block protections
    default: op
  unbreakable.trust:
    description: Allows trusting other players on blocks
    default: op
  unbreakable.untrust:
    description: Allows removing trust from players
    default: op
  unbreakable.region:
    description: Allows managing protected regions
    default: op
